export const ENDPOINTS = {
    POST_SIGNIN: '/HRMBackendTest/api/auth/signin',
    GET_PROJECTS_BY_EMPLOYEE: '/HRMBackendTest/project/projects-by-employee/271',
    GET_USERS_ACCESS: '/HRMBackendTest/menu/v1/users',
    GET_EMPLOYEES: '/HRMBackendTest/user',
    GET_ASSET_TYPE_BY_ID: '/HRMBackendTest/assest/total',
    GET_ASSET_LIST_SUMMARY: '/HRMBackendTest/assest/list',
    GET_ASSET_ALLOCATED_LIST_SUMMARY: '/HRMBackendTest/assest',
    GET_USERS_LIST: '/HRMBackendTest/user',
    GET_ASSET_ASSIGNED_TO_USER: '/HRMBackendTest/assest',
    GET_ASSET_REQUEST_PAGE_LIST: '/HRMBackendTest/assest/assestRequestList',
    GET_ASSET_ACCESS_REQUEST_PAGE_LIST: '/HRMBackendTest/api/access/requests/employee/271',
    GET_ASSET_ACCESS_REQUEST_PAGE_DL_LIST:'/HRMBackendTest/leave/ood/dl/list',
    GET_ASSET_ACCESS_REQUEST_STATUS_APPROVED: '/HRMBackendTest/api/access/types',
    GET_EMPLOYEES_DATA_V2: '/HRMBackendTest/api/access/accessesEmployeesDataV2',
    GET_ACCESS_REQUEST_TYPE_STATUS: '/HRMBackendTest/api/access/types',
    GET_STATUS_CATEGORY_PENDING: '/HRMBackendTest/assest/category',
    GET_STATUS_CATEGORY_ALL: '/HRMBackendTest/assest/category',
    GET_ACTIVE_PROJECTS:'/HRMBackendTest/project/getActiveProjects',
    GET_APPROVER_ASSET_REQUEST_LIST: '/HRMBackendTest/assest/v2/approverAssestRequestList',
    GET_ASSET_OWNER_TYPES:'/HRMBackendTest/assest/owner/types',
    GET_USERS: '/HRMBackendTest/user',
    GET_LEAVE_TYPES: '/HRMBackendTest/leave/v2/types',
    GET_EMPLOYEE_LEAVE_DETAILS: (leaveId: number | string) =>
        `/HRMBackendTest/leave/masterleave/${leaveId}`,
    GET_LEAVE_REQUEST: '/HRMBackendTest/leave',
    POST_APPLY_LEAVE: '/HRMBackendTest/leave/leaveApply',
    PUT_WITHDRAW_LEAVE: '/HRMBackendTest/leave/leave/withdraw',
    GET_MY_TEAM_LEAVE: '/HRMBackendTest/leave/leave/approver/manager',
    PUT_APPROVE_REJECT_LEAVE: '/HRMBackendTest/leave/us/leave/approve',

}